version: "3.7"

services:
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: migration
      MYSQL_USER: test
      MYSQL_PASSWORD: test
volumes:
  mysql_data:
